# build w3name-cli binaries for linux & windows
# TODO: trigger on github release action and upload binaries as release artifacts

on: [push]

name: Cargo build

jobs:
  build_linux_and_windows:
    name: Build for Linux & Windows 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - aarch64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}

  build_macos:
    name: Build for macOS
    runs-on: macos-11
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    steps:
      - name: install protobuf compiler
        run: brew install protobuf
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Cargo build
        run: cargo build --release --target ${{ matrix.target }}
        



