# Publish updated crates when a GH release is created

on:
  release:
    types: [created]

name: Cargo publish

jobs:
  cargo_publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: install protobuf compiler
        uses: arduino/setup-protoc@v1
        with:
          version: '3.20.2'
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - uses: katyo/publish-crates@v1
        with:
            registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
